### ISSUE TITLE
vat report

### ISSUE THREAD

**Issue by glennbeerten** [OCA/l10n-belgium#141]
Dear

Is it also possible to make a Belgium VAT report?

**Comment by rousseldenis** [comment]
@luc-demeyer @jdidderen-noviat Is it planned to do an equivalent here to l10n_be_reports (EE) ?

**Comment by ghost** [comment]
@rousseldenis On the Noviat side, we have a module that combines l10n_be and l10n_be_reports. The module is named [l10n_be_coa_multilang](https://github.com/Noviat/noviat-apps/tree/15.0/l10n_be_coa_multilang/). 

For now, it's a "concurrent" of l10n_be and we planned to integrate it properly with l10n_be and than extend l10n_be on the functional standpoint. 

Right now, we do not have plans to push it to OCA but I have no problem discussing it and seeing what can be done (I'll have to discuss this possibility with @luc-demeyer before considering putting it officially on the OCA side, since he maintains the module alone since the beginning of Noviat). 

If there's no hurry, I propose to discuss it at the OCA days in Liège if you'll be there too.

**Comment by luc-demeyer** [comment]
The 16.0 version of this module (not published yet) runs ‘technically’ together with l10n_be and l10n_be_reports but we do have a problem to deploy and publish it since the l10n_be_coa_multilang is AGPL and depends on OCA AGPL modules. The l10n_be_coa_multilang_oe module that allows to take advantage to the Odoo Enterprise features depends on AGPL modules as well as OEEL modules which is a combination that violates the Odoo license policies.
We are facing similar issues in other cases were we want to enhance both AGPL modules combined with Odoo Enterprise OEEL modules.

The only way around it (as I see it at this point in time) is that OCA changes from AGPL to LGPL (since I don't think Odoo is prepared to change their licensing policy).
I can hardly imagine that Noviat is the only OCA member experiencing this issue, hence maybe an agenda point for the upcoming OCA days.

**Comment by luc-demeyer** [comment]
@rousseldenis 
one more thing;
we will publish the 16.0 AGPL version of the l10n_be_coa_multilang module which now runs without conflict with l10n_be and includes the vat declaration, intracom declaration and customer listing (as well as NBB/BNB legal reports and a bunch of other features).

**Comment by victor-champonnois** [comment]
> @rousseldenis one more thing; we will publish the 16.0 AGPL version of the l10n_be_coa_multilang module which now runs without conflict with l10n_be and includes the vat declaration, intracom declaration and customer listing (as well as NBB/BNB legal reports and a bunch of other features).

That's great news ! We at Coop IT Easy would happily review the PR to OCA for this module.

**Comment by luc-demeyer** [comment]
@victor-champonnois 
we'll publish it via https://github.com/Noviat/noviat-apps (and @rousseldenis is not involved in this exercise).
I don't think we'll turn the code into a set of OCA modules for 16.0 (17.0 is more likely).

**Comment by vdewulf** [comment]
@luc-demeyer Good news to get your module compatible with l10n_be in version 16, that'd be awesome and we certainly are going to use your modules for the VAT declaration (in l10n_be_mis_reports in v12 and v14 but not in v16 anymore) + annual clients listing + intracomm declaration (those 2 reports being currently in l10n_be_vat_reports, module which will not be needed anymore).

When do you plan to get a testable PR on v16.0?
Could you make a sign here and ping @victor-champonnois or myself when it happens?
Thanks!

About the licences topic and limitation to propose your code to the OCA, I'm not a licence expert at all but this might be of interest for the community during the OCA Days. Don't hesitate to propose a "discussion" talk for the technical track:
https://odoo-community.org/event/oca-days-2023-liege-2023-11-06-2023-11-07-143/track_proposal

See you in 3 months in real life :)

**Comment by victor-champonnois** [comment]
We did some testing with @vdewulf to see if we could use `l10n_be_coa_multilang` for our clients migrating to v16. The module is great and adds a lot more functionality and precisions compared to l10n_be. 
However, the module uses it's own account.tax.template, and the VAT reports is based on it. So currently, if you migrate a "l10n_be" DB to v16 it's not possible to use directly the reports without modifying the tax tags.  
According to @luc-demeyer, making this compatibility work "out of the box" in the roadmap. This is great!

For now, at Coop IT Easy,  we'll port `l10n_be_vat_report` and use `mis-report `for VAT reports (national, intracomm and subjected partner listing), because we want to start migrating clients quickly.

**Comment by victor-champonnois** [comment]
@sbidoul can `l10n_be_vat_report` be added to the list of [migration 16 issue](https://github.com/OCA/l10n-belgium/issues/149) ?
