### ISSUE TITLE
Which python lib is used for coda ?

### ISSUE THREAD

**Issue by houssine78** [OCA/l10n-belgium#77]
Hi folks,

I'm on the way to port account_bank_statement_import_coda to v12 and I try to figure out which python library is used by the module account_bank_statement_import_coda to parse coda file

According the manifest the lib is called coda this lib name refers to [this lib](https://pypi.org/project/coda/) which has nothing to do with coda file parsing.
when I read the description [here](https://github.com/coopiteasy/l10n-belgium/blob/11.0/account_bank_statement_import_coda/readme/DESCRIPTION.rst) it refers to pycoda which is the lib developed by Acsone.

Just for info, I found a [third](https://pypi.org/project/febelfin-coda/)lib developed by Tryton 

If @lmignon or @sbidoul could give me an answer it would be great

Thanks !

**Comment by sbidoul** [comment]
It's pycoda by acsone.

Odoo manifests until Odoo 12 refer to the package name used in the `import` statement, not their PyPI name. The good news is that it's improved for v13 (since [yesterday](https://github.com/odoo/odoo/pull/25549)), and we'll be able to refer to pycoda in the manifest, avoiding confusion.

It's a bit unfortunate that Tryton developed it's own instead of contributing to pycoda.

**Comment by houssine78** [comment]
Thanks Stéphane !
